/** @type {import('tailwindcss').Config} */
const sans = [
  "Geist",
  "Noto Sans SC",
  "WenQuanYi Micro Hei",
  "PingFang SC",
  "Hiragino Sans GB",
  "Microsoft YaHei",
  "sans-serif",
];

const mono = ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"];

module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#7bd0ff",
        "inverse-surface": "#e1e2e9",
        "surface-container": "#1d2025",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-high": "#272a2f",
        "surface-tint": "#bfc1ff",
        "inverse-on-surface": "#2e3036",
        "on-primary-fixed-variant": "#3236a9",
        "on-secondary-container": "#00374d",
        outline: "#908f9f",
        "on-surface-variant": "#c7c5d5",
        "on-tertiary-container": "#00311f",
        "on-tertiary": "#003824",
        primary: "#bfc1ff",
        "on-surface": "#e1e2e9",
        "tertiary-container": "#00a572",
        "outline-variant": "#464653",
        "surface-container-lowest": "#0b0e13",
        "secondary-fixed": "#c4e7ff",
        "inverse-primary": "#4b51c2",
        tertiary: "#4edea3",
        surface: "#101418",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "surface-dim": "#101418",
        "on-background": "#e1e2e9",
        "on-primary-fixed": "#03006d",
        secondary: "#7bd0ff",
        "primary-container": "#7f85f9",
        "primary-fixed-dim": "#bfc1ff",
        "on-secondary-fixed": "#001e2c",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#004c69",
        "tertiary-fixed": "#6ffbbe",
        background: "#101418",
        "on-primary-container": "#0d0b8e",
        error: "#ffb4ab",
        "primary-fixed": "#e1e0ff",
        "secondary-container": "#00a6e0",
        "on-primary": "#171994",
        "surface-bright": "#36393f",
        "surface-variant": "#32353a",
        "on-error": "#690005",
        "on-secondary": "#00354a",
        "surface-container-low": "#191c21",
        "surface-container-highest": "#32353a",
        pi: {
          bg: "#0b0e14",
          surface: "#11141a",
          card: "#161922",
          cardHover: "#1c202b",
          border: "#242835",
          borderLight: "#32384a",
          accent: "#7c82f6",
          accentHover: "#6a70e8",
          accentMuted: "#2b2f48",
          muted: "#8b949e",
          text: "#e6edf3",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        xs: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xl": "1.5rem",
        "space-xs": "0.25rem",
        margin: "1rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-sm": "0.5rem",
        gutter: "0.75rem",
      },
      fontFamily: {
        "headline-lg": sans,
        "headline-md": sans,
        "headline-sm": sans,
        "body-lg": sans,
        "body-md": sans,
        "body-sm": sans,
        "label-md": sans,
        "label-sm": sans,
        "label-xs": sans,
        "code-md": mono,
        "code-sm": mono,
      },
      fontSize: {
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["1.0625rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["0.9375rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.375rem", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "label-md": ["0.8125rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["0.75rem", { lineHeight: "0.875rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-xs": ["0.6875rem", { lineHeight: "0.75rem", letterSpacing: "0.04em", fontWeight: "600" }],
        "code-md": ["0.8125rem", { lineHeight: "1.375rem", fontWeight: "400" }],
        "code-sm": ["0.75rem", { lineHeight: "1.25rem", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
